apiVersion: v1
kind: Service
metadata:
  name: demo-java-app-service
spec:
  selector:
    app: demo-java-app  # Must match the label in the deployment
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 8080  # Internal port
  type: NodePort
