apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java-app
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: demo-java-app
  template:
    metadata:
      labels:
        app: demo-java-app
    spec:
      containers:
        - name: demo-java-app
          image: demo-java-app:latest  # Docker image name
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
